### ISSUE TITLE
Downloaded Filename Mismatch?

### ISSUE THREAD

**Issue by 4NZK7C** [Electronickss/TheaterTrailers#14]
I am trying to use the script to download trailers but it seems to be choking on the downloaded file names. The script runs until it downloads the first trailer. I then stops and reports No such file or directory. The two files created are:

C:\GitHub\TheaterTrailers\Trailers\BrightBurn (2019)\BrightBurn (2019).f137.mp4
C:\GitHub\TheaterTrailers\Trailers\BrightBurn (2019)\BrightBurn (2019).mp4.f140

It then reports:
IOError: [Errno 2] No such file or directory: u'C:\\GitHub\\TheaterTrailers\\Trailers\\BrightBurn (2019)\\BrightBurn (2019).mp4'

It looks like there is a mismatch between the expected filename and the actual file name. I have changed the maximum number of downloads several times just in case it was stopping on a particular file. Each time the script stops after the first trailer is downloaded.  Any help would be appreciated.

I'm using Python 2.7.16 on Win 10 Pro

The output is below

C:\Users\XXXXXXXXXXXXX>
C:\Users\XXXXXXXXXXXXX>py -2 "C:\GitHub\TheaterTrailers\theatertrailers.py"
2019-04-04 17:45:19,624 - INFO - ValueError No JSON object could be decoded
2019-04-04 17:45:19,625 - INFO - Cache file empty
[youtube:playlist] PLScC8g4bqD47c-qHlsfhGH3j6Bg7jzFy-: Downloading webpage
[download] Downloading playlist: HOT New Trailers & Movieclips Exclusives
[youtube:playlist] playlist HOT New Trailers & Movieclips Exclusives: Downloading 30 videos
[download] Downloading video 1 of 30
[download] Downloading video 2 of 30
[download] Downloading video 3 of 30
[download] Downloading video 4 of 30
[download] "Wonder Park Exclusive Movie Clip - Rocket (2019) | Movieclips Coming Soon" title did not match pattern ".*\btrailer\b.*"
[download] Downloading video 5 of 30
[download] Downloading video 6 of 30
[download] Downloading video 7 of 30
[download] Downloading video 8 of 30
[download] "Us Movie Clip - The Tethers (2019) | Movieclips Coming Soon" title did not match pattern ".*\btrailer\b.*"
[download] Downloading video 9 of 30
[download] Downloading video 10 of 30
[download] Downloading video 11 of 30
[download] Downloading video 12 of 30
[download] "Missing Link Exclusive Featurette - Zach Galifianakis is Mr. Link (2019) | Movieclips Coming Soon" title did not match pattern ".*\btrailer\b.*"
[download] Downloading video 13 of 30
[download] Downloading video 14 of 30
[download] Downloading video 15 of 30
[download] Downloading video 16 of 30
[download] Downloading video 17 of 30
[download] Downloading video 18 of 30
[download] "Shazam! Exclusive Movie Clip - A Wizard Made Me Look Like This! (2019) | Movieclips Trailers" title did not match pattern ".*\btrailer\b.*"
[download] Downloading video 19 of 30
[download] Downloading video 20 of 30
[download] "Avengers: Endgame Featurette - We Lost (2019) | Movieclips Trailers" title did not match pattern ".*\btrailer\b.*"
[download] Downloading video 21 of 30
[download] Downloading video 22 of 30
[download] "Master Z: The Ip Man Legacy Exclusive Movie Clip - Tin Chi vs. Kwan Fight (2019) | Movieclips" title did not match pattern ".*\btrailer\b.*"
[download] Downloading video 23 of 30
[download] Downloading video 24 of 30
[download] Downloading video 25 of 30
[download] Downloading video 26 of 30
[download] Downloading video 27 of 30
[download] "Game of Thrones Season 8 Teaser | 'Aftermath' | Rotten Tomatoes TV" title did not match pattern ".*\btrailer\b.*"
[download] Downloading video 28 of 30
[download] "Avengers: Endgame First Look (2019) | Movieclips Trailers" title did not match pattern ".*\btrailer\b.*"
[download] Downloading video 29 of 30
[download] Downloading video 30 of 30
[download] Finished downloading playlist: HOT New Trailers & Movieclips Exclusives
2019-04-04 17:45:21,168 - INFO - querying the movie db for Game of Thrones Season 8
2019-04-04 17:45:21,420 - WARNING - Game of Thrones Season 8 is missing its release date
2019-04-04 17:45:21,515 - INFO - querying the movie db for Master Z The Ip Man Legacy Exclusive
2019-04-04 17:45:21,766 - WARNING - Master Z The Ip Man Legacy Exclusive is missing its release date
2019-04-04 17:45:21,923 - INFO - querying the movie db for BrightBurn
2019-04-04 17:45:22,174 - INFO - Creating Cache
2019-04-04 17:45:22,184 - INFO - downloading BrightBurn from TLaa5wjEtUE
[youtube] TLaa5wjEtUE: Downloading webpage
[youtube] TLaa5wjEtUE: Downloading video info webpage
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
[download] Destination: C:\GitHub\TheaterTrailers\Trailers\BrightBurn (2019)\BrightBurn (2019).f137.mp4
[download] 100% of 18.30MiB in 00:02
[download] Destination: C:\GitHub\TheaterTrailers\Trailers\BrightBurn (2019)\BrightBurn (2019).mp4.f140
[download] 100% of 2.55MiB in 00:00
Traceback (most recent call last):
  File "C:\GitHub\TheaterTrailers\theatertrailers.py", line 464, in <module>
    main()
  File "C:\GitHub\TheaterTrailers\theatertrailers.py", line 140, in main
    updateCache(MovieDict[item]['url'], title, trailerYear)
  File "C:\GitHub\TheaterTrailers\theatertrailers.py", line 283, in updateCache
    videoDownloader(string, passedTitle, yearVar)
  File "C:\GitHub\TheaterTrailers\theatertrailers.py", line 308, in videoDownloader
    os.path.join(trailerLocation, '{0} ({1})'.format(passedTitle, yearVar), '{0} ({1})-trailer.mp4'.format(passedTitle, yearVar))
  File "C:\Python27\lib\shutil.py", line 153, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'C:\\GitHub\\TheaterTrailers\\Trailers\\BrightBurn (2019)\\BrightBurn (2019).mp4'

**Comment by 4NZK7C** [comment]
I figured this out right after I posted. I did not have ffmpeg in my path.
