### ISSUE TITLE
Errror when running script

### ISSUE THREAD

**Issue by Chito24** [Electronickss/TheaterTrailers#17]
Removed it all, re-installed and still get the same error when i run the script:

Traceback (most recent call last):
  File "F:\Python27\Scripts\TheaterTrailers-master\TheaterTrailers-master\theaterTrailers.py", line 464, in <module>
    main()
  File "F:\Python27\Scripts\TheaterTrailers-master\TheaterTrailers-master\theaterTrailers.py", line 140, in main
    updateCache(MovieDict[item]['url'], title, trailerYear)
  File "F:\Python27\Scripts\TheaterTrailers-master\TheaterTrailers-master\theaterTrailers.py", line 255, in updateCache
    shutil.rmtree(jsonDict[passedSmallTitle]['path'])
  File "F:\Python27\lib\shutil.py", line 262, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "F:\Python27\lib\shutil.py", line 260, in rmtree
    names = os.listdir(path)
WindowsError: [Error 3] The system cannot find the path

**Comment by schmitzCatz** [comment]
same problem within freeBsd ;(
