### ISSUE TITLE
Problem after downloading video

### ISSUE THREAD

**Issue by piegus96** [Electronickss/TheaterTrailers#18]
Hi i have python 2.7 and after run script i have this error:

[download] Downloading video 377 of 382
[download] Downloading video 378 of 382
[download] Downloading video 379 of 382
[download] Downloading video 380 of 382
[download] Downloading video 381 of 382
[download] Downloading video 382 of 382
[download] Finished downloading playlist: HOT New Trailers & Movieclips Exclusives
2019-09-22 11:00:44,930 - INFO - querying the movie db for Alita Battle Angel
2019-09-22 11:00:45,180 - ERROR - ValueError for Alita Battle Angel invalid literal for int() with base 10: '' 119
2019-09-22 11:00:45,181 - INFO - Creating Cache
2019-09-22 11:00:45,632 - INFO - querying the movie db for Fantastic Beasts The Crimes of Grindelwald
2019-09-22 11:00:45,884 - INFO - Creating New Entry
2019-09-22 11:00:46,365 - INFO - querying the movie db for Avengers Infinity War
2019-09-22 11:00:46,615 - INFO - Creating New Entry
2019-09-22 11:00:47,118 - INFO - querying the movie db for Deadpool 2
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\TheaterTrailers\theaterTrailers.py", line 464, in <module>
    main()
  File "C:\Users\Adam\Desktop\TheaterTrailers\theaterTrailers.py", line 112, in main
    releaseDate = s['release_date']
KeyError: u'release_date'

**Comment by henriquelbsouza** [comment]
Exact same error here, anyone able to fix that?

**Comment by henriquelbsouza** [comment]
I "fixed" it by "ignoring" the document when it doesn't have the release_date...

On line 112 I replaced the 

`s['release_date']`
with 
`s.get('release_date', '1900-01-01')`

the code is running... not sure what is the impact of that, maybe I loose all trailers at the end of the run :P

I may do a better job on that later, I don't have the proper time right now...

@Electronickss if you can give us some insight :)

**Comment by henriquelbsouza** [comment]
It download, the trailer files are there BUT plex doesn't seem to find it, or it just doesn't index it :(

Anyone has any idea? :)

Edit: Made it work by adding the Trailers folder to the local media assets and in the library itself...

**Comment by TristBella** [comment]
replace what is in your file with this
[theaterTrailers.txt](https://github.com/Electronickss/TheaterTrailers/files/6013437/theaterTrailers.txt)
