### ISSUE TITLE
Errors at end of script nothing downloaded

### ISSUE THREAD

**Issue by goku-son** [Electronickss/TheaterTrailers#19]
When I run the script I get these errors and nothing downloads:

[download] Finished downloading playlist: HOT New Trailers & Movieclips Exclusives
2019-12-14 19:56:55,538 - INFO - querying the movie db for Fantastic Beasts The Crimes of Grindelwald
2019-12-14 19:56:55,792 - INFO - Creating Cache
2019-12-14 19:56:56,039 - INFO - querying the movie db for Incredibles 2
2019-12-14 19:56:56,293 - INFO - Creating New Entry
2019-12-14 19:56:56,556 - INFO - querying the movie db for Ralph Breaks the Internet
2019-12-14 19:56:56,811 - INFO - Creating New Entry
2019-12-14 19:56:57,079 - INFO - querying the movie db for The Lego Movie 2 The Second Part
2019-12-14 19:56:57,342 - INFO - Creating New Entry
2019-12-14 19:56:57,596 - INFO - querying the movie db for Bumblebee
Traceback (most recent call last):
  File "theaterTrailers.py", line 464, in <module>
    main()
  File "theaterTrailers.py", line 112, in main
    releaseDate = s['release_date']
KeyError: u'release_date'

**Comment by haidavila** [comment]
Same error with me

**Comment by TristBella** [comment]
same here....pretty much useless at this point

**Comment by TristBella** [comment]
replace what is in your file with this
[theaterTrailers.txt](https://github.com/Electronickss/TheaterTrailers/files/6013437/theaterTrailers.txt)
