### ISSUE TITLE
Thanks for the update but I am having issues

### ISSUE THREAD

**Issue by apperrault** [Electronickss/TheaterTrailers#3]
I downloaded the most recent version and I am having issues.  I have updated my trailers.conf with what I believe to be the correct info and when I run it, I get the following errors:

`Traceback (most recent call last):
  File "D:\GitHub\TheaterTrailers\theaterTrailers.py", line 448, in <module>
    main()
  File "D:\GitHub\TheaterTrailers\theaterTrailers.py", line 139, in main
    updateCache(MovieDict[item]['url'], title, trailerYear)
  File "D:\GitHub\TheaterTrailers\theaterTrailers.py", line 272, in updateCache
    addToRadarr(passedTitle, yearVar, jsonDict[passedSmallTitle]['TMDB ID'], rad
arrRootFolderPath)
  File "D:\GitHub\TheaterTrailers\theaterTrailers.py", line 159, in addToRadarr
    "rootFolderPath": "{0}".format(radarrRootFolderPath)
  File "C:\Python27\lib\requests\api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(10061, 'No co
nnection could be made because the target machine actively refused it'))
`
Any thought what is causing this?  I can post my config file (with the API keys redacted of course.)

thanks

app

**Comment by Electronickss** [comment]
Delete the cache. I added a new variable in the cache file so that if you are using radarr it can push movies to your wanted items but the error I believe is saying that doesn't exist

**Comment by Electronickss** [comment]
You can just remove the whole folder or delete the JSON file within it. The script will recreate it

**Comment by Electronickss** [comment]
The more i think about it, I should probably add a check at the beginning of the script to check that all variables in the cache are there that I'd be looking for throughout and delete it if they aren't, then let it rebuild it
