### ISSUE TITLE
Script failure after downloading playlist

### ISSUE THREAD

**Issue by beltic** [Electronickss/TheaterTrailers#7]
hiya..

I am attempting to run these scripts on a windows 10 box using Python 3.7. Most of the scripting errors were easy to fix (mostly cuz my editor converted spaces to tabs, and I had to replace that..)

however - once it started to download the playlist, I got the following:
....<clip>....
[download] Downloading video 278 of 278
[download] Finished downloading playlist: HOT New Trailers & Movieclips Exclusives
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\TheaterTrailers\theaterTrailers.py", line 463, in <module>
    main()
  File "C:\Program Files (x86)\Plex\TheaterTrailers\theaterTrailers.py", line 94, in main
    infoDownloader(youtubePlaylist)
  File "C:\Program Files (x86)\Plex\TheaterTrailers\theaterTrailers.py", line 334, in infoDownloader
    MovieVar = MovieVar.replace(':', '')
TypeError: a bytes-like object is required, not 'str'3

I am not a coder, so searching the net really didnt give me enough to go on. I would really like to see this working.

thank you.

**Comment by mdbxz** [comment]
Dropping the encode method worked for me, so:
x['title'].encode('ascii',errors='ignore')
becomes
x['title']
